GET http://localhost:4001/health

###
POST http://localhost:4001
Content-Type: application/json

{
  "name": "Tamim",
  "country": "BD",
  "rank": 2
}

###
GET http://localhost:4001

###

GET http://localhost:4001/v1r2U6R0r

###

GET http://localhost:4001/4UE1pa_qD